spring.application.name=shop-modular-monolith
server.port=${PORT:8080}

spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres}
spring.datasource.password=${SUPABASE_DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.open-in-view=false

legacysupply.base-url=${LS_BASE_URL:https://legacysupply.onrender.com/api/v1}
legacysupply.client-id=${LS_CLIENT_ID:22-2068-823}
legacysupply.api-key=${LS_API_KEY:}

